### ISSUE TITLE
openvino/workbench 2022.1 fails to download aclnet-int8 model

### ISSUE THREAD

**Issue by dnoliver** [openvinotoolkit/workbench#92]
To reproduce:
1. Start workbench
2. import a model
3. select aclnet-int8
4. click download

Expected: model should be downloaded
Actual: Error is shown, see screen

![image](https://user-images.githubusercontent.com/7730267/175400159-262a3a63-9395-4cf1-a62b-7f5122804446.png)

**Comment by artyomtugaryov** [comment]
Hello, @dnoliver! Thank you for using OpenVINO DL Workbench!
Can you try to download the model again and after the fail get the server logs. It will help to understand where is the problem.
The instruction about downloading logs you can find by the link - https://docs.openvino.ai/latest/workbench_docs_Workbench_DG_Troubleshooting.html

**Comment by dnoliver** [comment]
Find the log in attachments 

[server.log](https://github.com/openvinotoolkit/workbench/files/9454435/server.log)

**Comment by yatarkan** [comment]
Hello @dnoliver! 
According to the model description: 
> The AclNet-int8 model is quantized and fine-tuned with NNCF variant of [AclNet](https://docs.openvino.ai/latest/omz_models_model_aclnet.html#doxid-omz-models-model-aclnet) model, which is designed to perform sound classification.
DL Workbench does not support sound classification use case, so AclNet will be removed from the available models list in DL Workbench UI.
